config/routes.rb
Rails.application.routes.draw do
  get 'competitions',to:'competitions#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
	devise_for :users
	root 'routes#root'
	resources :exams,except:[:show,:index]
	get 'practise/:id', to: 'exams#show', as: 'practise'
	get 'practise', to: 'exams#index'
	resources :scores
	get '/dashboard',to: 'welcomes#index'
	get '/performance', to: 'scores#index'
	resources :competitions
	get 'increase_i', to: 'competitions#increase_i'
	get 'time_finished', to: 'competitions#time_finished'
end

app/models/competition.rb
# == Schema Information
#
# Table name: competitions
#
#  id            :integer          not null, primary key
#  name          :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  category_id   :integer
#  slug          :string
#  starting_date :datetime
#

class Competition < ApplicationRecord
		belongs_to :category
		extend FriendlyId
    friendly_id :name, use: [:slugged, :history]
    def should_generate_new_friendly_id?
        new_record? || slug.blank? || name_changed?
    end
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController

  def index
		@start=Time.now.beginning_of_week(start_day= :sunday)
		@end=Time.now.end_of_week(start_day=:sunday)
		@range=@start..@end
		# @this_week_competition=Competition.where(starting_date: @range)
		if Competition.where(starting_date: @range).nil?
			@id= 	Competition.last.id
			@this_week_competition = Competition.create(name: @id, category_id: rand(1..5), starting_date: @start)
		else
			@this_week_competition=Competition.where(starting_date: @range)
		end

		@visible_score=Competescore.where(user_id: current_user.id, created_at: (Time.now-100.year)..@start).last
		@recent_scores=Competescore.where(user_id:current_user.id, created_at: (Time.now-100.year)..@start).last(6).to_a
		@recent_scores.pop
		if @visible_score
			if Time.now > @visible_score.created_at.end_of_week(start_day= :sunday)
				@visible_score
			else
				@visible_score=nil
			end
		end
  end

	def new
		@competition=Competition.new	
	end
	def create
		@competition=Competition.create(competition_params)
		if @competition.save
			flash[:notice]="success!"
			redirect_to new_competition_path
		else
			render 'new'
		end
	end

	def increase_i
		if params[:i].blank?
			@i=0
			$counting=0
		else
			@i=params[:i].to_i+1
			$counting=$counting+1
		end
		# if @i!=100
		if @i!=5
			@question = $rand_question[@i].question_content
			@options= $rand_question[@i].answers
			if params[:user_choice].present?
				@answer=Answer.find_by(id: params[:user_choice])
				if @answer.correct
					$compete_score=$compete_score.to_i+1
				end
			end
		else
			Competescore.create(score:$compete_score, user_id: current_user.id, competition_id: $competition.id)

			@counter=1
			Competescore.where(competition_id: $competition.id).sort_by{|data| data.score}.reverse!.each do |competescore|
				competescore.rank=@counter
				competescore.save
				@counter=@counter+1
			end
		end
	end

	def time_finished
			Competescore.create(score:$compete_score, user_id: current_user.id, competition_id: $competition.id)
			@counter=1
			Competescore.where(competition_id: $competition.id).sort_by{|data| data.score}.reverse!.each do |competescore|
				competescore.rank=@counter
				competescore.save
				@counter=@counter+1
			end
	end

	def show
		$competition=nil
		$competition=Competition.friendly.find(params[:id])
		@already_competed=Competescore.find_by(user_id: current_user.id, competition_id: $competition.id)
		$rand_question=Question.order("RANDOM()").limit(5)
		$compete_score=nil
	end

	private

	def competition_params
		params.require(:competition).permit(:name,:category_id,:starting_date)
	end

end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/_competitioncontent.html.erb
<style type="text/css" media="">
.tabs{
	overflow:hidden;
}
i{
	vertical-align:middle;
}
.heading{
	font-family:Ubuntu;
	font-size:24px;
	color:#fff;
	padding:14px 20px;
	letter-spacing:.5px;
	background:#f0f0f0;
}	
@media (min-width:887px){
}
@media (max-width:601px){

	 div.heading{
		margin-top:-10px!important;
	}
}
ul.tabs li a{
	font-size:16px!important;

}
.card-title{
	font-weight:bold !important;
}
</style>

<div class="heading row red lighten-1" style="margin-bottom:0;margin-left:-10px;font-weight:bold;">
	<center >
Competitions	
	</center>
</div>

<div class="row">
    <div class="col s12" style="padding:0;">
      <ul class="tabs">
        <li class="tab col s4 disabled"><a href="#test1">Previous week</a></li>
        <li class="tab col s4"><a class="active" href="#test2">This week</a></li>
        <li class="tab col s4 disabled"><a href="#test3">Next week</a></li>
      </ul>
    </div>
		<div id="test1" class="col s12">
			Test 1
		</div>
	<div id="test2" class="col s12" style="">
<div class="row" style="margin-top:40px;">
<div class="col s12 m6 subjects ">
   <div class="card" style="background-color:white;">
      <div class="card-content">
				<span class="card-title"><% if @this_week_competition  %><%= @this_week_competition[0].name %><% end  %></span>
				<ul class="competition_feature" style="padding-left:30px">

					<li><i class="material-icons">arrow_forward</i>Time: 2 hour</li>
					<li><i class="material-icons">arrow_forward</i>Related: IOE model</li>
					<li><i class="material-icons">arrow_forward</i>Prize: (N/A)</li>
				</ul>
				<div class="card-action" style="padding-bottom:0">
					<% if @this_week_competition  %>
					<%= link_to 'Compete', competition_path(@this_week_competition[0])  %>	
				<% end  %>
					<!-- <a href="#">Invite</a> -->
				</div>
      </div>
   </div>
</div>

<div class="col s12 m6 subjects ">
   <div class="card" style="background-color:white;">
      <div class="card-content">
				<span class="card-title">Last Exam Summary</span>
				<ul class="competition_feature" style="padding-left:30px">

					<li><i class="material-icons">arrow_forward</i>Score:
						<%  if @visible_score %><%= @visible_score.score  %><% else  %><span>N/A</span><% end  %></li>
						<li><i class="material-icons">arrow_forward</i>Rank:<%  if @visible_score %><%= @visible_score.rank %><% else  %><span>N/A</span><% end  %></li>
						</li>
					<li><i class="material-icons">arrow_forward</i>Progress: N/A</li>
				</ul>
				<div class="card-action" style="padding-bottom:0">
						 <%= link_to '<p style="margin:0;font-size:17px;">View Details</p>'.html_safe, '#modal1', class:"waves-effect waves-light main-btn modal-trigger" %>
				</div>
      </div>
   </div>
</div>


  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">


</div>

	</div>
	<div id="test3" class="col s12">
		Test 3
	</div>
  </div>

<div class="heading row red lighten-1" style="margin-left:-10px;font-weight:bold;">
	<center >
Your recent Competitions	
	</center>
</div>
<div class="row">
	<div class="col s12">
		<div class="card">
			<div class="">
 <table class="bordered highlight centered ">
        <thead>
          <tr>
              <th>Name</th>
              <th>Rank</th>
              <th>Score</th>
          </tr>
        </thead>

        <tbody>
				 <% if @recent_scores  %>
					<% @recent_scores.each do |last_scores| %>
						<tr>
							<td><%= Competition.find_by(id: last_scores.competition_id).name  %></td>
							<td><%=  last_scores.rank %></td>
							<td><%= last_scores.score  %></td>
						</tr>
					<% end  %>
				<% end  %>
        </tbody>
      </table>
			</div>
		</div>
	</div>
</div>
<script charset="utf-8">
	
  $(document).ready(function(){
		$('ul.tabs').tabs();
  });
        
</script>

app/views/competitions/index.html.erb
<header id="header" class="">
   <div class="navbar-fixed">
      <nav class="">
         <div class="nav-wrapper">
            <ul class="left">
               <li>
                  <span class="logo-wrapper"><a href="#" class="brand-logo" style="text-decoration:none;padding:0 !important;"><span style="font-family:georgia;font-size:25px;color:#fff;">&nbsp;&nbsp;EntrancePrep</span></a>
               </li>
            </ul>
            <div class="header-search-wrapper hide-on-med-and-down">
               <i class="material-icons">search</i>
               <input type="text" name="Search" class="header-search-input" style="border-bottom:rgb(244, 67, 54);padding-left:60px;color:white;background-color:rgb(244, 67, 54);border-radius:50px;" placeholder="Search">
            </div>
         </div>
      </nav>
   </div>
</header>
<div id="main">
<div class="wrapper">
   <script>
      $(".sidebar-collapse").sideNav();
   </script>
   <div >
      <section id="content" style="padding-top:64px">
         <%= render 'shared/flash' %>
         <style>
            .pad-top i{color:white;font-size: 7em !important;}
         </style>
         <div class="row mybox-container">
            <%= render 'competitioncontent' %>
         </div>
      </section>
   </div>
</div>

app/views/competitions/show.html.erb
<% if @already_competed %>
	<!-- <h1 style="background:white;display:inline&#45;block;">You have already competed in this examination.</h1> -->
$('html').append('<div class="whole-page-div"><center class="blue" style="padding:50px;color:white;margin:30px;font-size:16px;">You have already competed in this examination. Wait till next Sunday to get the result</center></div>');
<% else  %>
<div class="start whole-page-div">
	<a href="/increase_i" data-remote="true" class="btn start-btn">Compete</a>
</div>
<div class="row" style="margin:30px;">
	<div class="col time m6 s12">
		<center>
				<span class="btn blue">
					Time Remaining: <span class="blue"></span>
			</span>
	</center>
</div>

<div class="col attempted m6 s12">
	<center>
		<span class="btn purple">Attempted: <span class="counting"></span>/100</span>
		</center>
</div>
</div>
<% end  %>
<p></p>
<script charset="utf-8">
$(document).ready(function(){
	$('.start-btn').click(function(){

	$('span.btn.blue span').countdown({until: +1999,format:'MS',compact: true,onTick: highlightLast5,onExpiry: expired});
	function expired(){
		$('.next').attr("href",'/time_finished');
		$('.next')[0].click();
	}

	function highlightLast5(periods) { 
    if ($.countdown.periodsToSeconds(periods) === 5) { 
        $(this).addClass('red'); 
				$(this).css('color','white');
    } 
	}
	});
});
</script>

app/views/competitions/time_finished.js.erb
$('p').remove();
$('html').append('<div class="whole-page-div"><center class="blue" style="padding:50px;color:white;margin:30px;">You have successfully competed in this examination. Please wait till Sunday to hear your result</center></div>');