config/routes.rb
Rails.application.routes.draw do
  get 'competitions',to:'competitions#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
	devise_for :users
	root 'routes#root'
	resources :exams,except:[:show,:index]
	get 'practise/:id', to: 'exams#show', as: 'practise'
	get 'practise', to: 'exams#index'
	resources :scores
	get '/dashboard',to: 'welcomes#index'
	get '/performance', to: 'scores#index'
	resources :competitions
	get 'increase_i', to: 'competitions#increase_i'
	get 'time_finished', to: 'competitions#time_finished'
end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id             :integer          not null, primary key
#  answer_content :string
#  correct        :boolean
#  question_id    :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Answer < ApplicationRecord
  belongs_to :question
	# validates :answer_content, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  category   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ApplicationRecord
	has_many :exams, dependent: :destroy
	validates :category, presence: true
end

app/models/competescore.rb
# == Schema Information
#
# Table name: competescores
#
#  id             :integer          not null, primary key
#  score          :integer
#  user_id        :integer
#  competition_id :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  rank           :integer
#

class Competescore < ApplicationRecord
  belongs_to :user
  belongs_to :competition
end

app/models/competition.rb
# == Schema Information
#
# Table name: competitions
#
#  id            :integer          not null, primary key
#  name          :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  category_id   :integer
#  slug          :string
#  starting_date :datetime
#

class Competition < ApplicationRecord
		belongs_to :category
		extend FriendlyId
    friendly_id :name, use: [:slugged, :history]
    def should_generate_new_friendly_id?
        new_record? || slug.blank? || name_changed?
    end
end

app/models/exam.rb
# == Schema Information
#
# Table name: exams
#
#  id          :integer          not null, primary key
#  name        :string
#  category_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  slug        :string
#

class Exam < ActiveRecord::Base
    has_many :questions, dependent: :destroy
		accepts_nested_attributes_for :questions, allow_destroy: true, reject_if: :all_blank
		extend FriendlyId
    friendly_id :name, use: [:slugged, :history]
    def should_generate_new_friendly_id?
        new_record? || slug.blank? || name_changed?
    end
    has_many :scores, dependent: :destroy
    belongs_to :category

    # validates :name, :category, :questions, presence: true

end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id               :integer          not null, primary key
#  question_content :string
#  exam_id          :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Question < ApplicationRecord
	belongs_to :exam
	belongs_to :competition
	has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers, allow_destroy: true, reject_if: :all_blank
	# validates :question_content, presence: true
	# validates :answers, presence: true
end

app/models/recent_score.rb
# == Schema Information
#
# Table name: recent_scores
#
#  id          :integer          not null, primary key
#  user_id     :integer
#  exam_id     :integer
#  temp        :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer
#

class RecentScore < ApplicationRecord
  belongs_to :user
  belongs_to :exam
end

app/models/score.rb
# == Schema Information
#
# Table name: scores
#
#  id          :integer          not null, primary key
#  score_value :integer
#  user_id     :integer
#  exam_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer
#

class Score < ApplicationRecord
  belongs_to :user
  belongs_to :exam
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  provider               :string
#  uid                    :string
#  username               :string
#  admin                  :boolean
#  avatar_file_name       :string
#  avatar_content_type    :string
#  avatar_file_size       :integer
#  avatar_updated_at      :datetime
#

class User < ApplicationRecord

has_paper_trail
# has_attached_file :avatar, styles: { medium: "300x300>", thumb: "40x40>" }, default_url: "/images/:style/missing.png"
  # validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
# validates :username, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable#,:omniauthable, :omniauth_providers => [:facebook]

def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    # user.username = auth.info.name   # assuming the user model has a name
    # user.avatar= auth.info.image # assuming the user model has an image
    # If you are using confirmable and the provider(s) you use validate emails, 
    # uncomment the line below to skip the confirmation emails.
    user.skip_confirmation!
  end
end

def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController

  def start
  end

  def index
		unless params[:category] =="Physics" || params[:category]=="Maths" || params[:category]=="Chemistry"|| params[:category]=="English"|| params[:category]=="Aptitute"
			redirect_to dashboard_path
		end
		@category = Category.find_by(category: params[:category])
    @practises=Exam.where(category: @category)
  end

 	def show
	  		   begin
      @exam=Exam.friendly.find(params[:id])
			@questions=@exam.questions
			# render json:@questions
		total_score = 0
		average_score = 0
			 Score.where(user_id: current_user.id, exam_id: @exam.id).each do |each_score|
			 	total_score = each_score.score_value.to_i + total_score.to_i
			 	average_score = total_score/5
			 end
			 @total_score=total_score
			 @average_score=average_score
    rescue ActiveRecord::RecordNotFound
      redirect_to root_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def start_exam
    unless params[:category].blank?
      @category_id = Category.find_by(category: params[:category]).id
      @exams=Exam.where(category_id: @category_id)
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/ranking_helper.rb
module RankingHelper
end

app/helpers/recent_score_helper.rb
module RecentScoreHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/exams/_answer_fields.html.erb
<div class="nested-fields">  
  <%= f.label :answer_content, "Answer" %>
  <%= f.text_area :answer_content %>
  <%= f.label "Correct Answer?" %>
  <%= f.check_box :correct %>
  <%= link_to_remove_association "remove", f %>
</div>

app/views/exams/_form.html.erb
<%= simple_form_for @exam do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name, :id => 'h' %>
  </div>
  <div> 
    <style>
      .select-wrapper span, .select-wrapper ul, .select-wrapper input {
        display:none;
      }
    </style>
    <%= f.collection_select :category_id, Category.all, :id, :category, {prompt:"Select a category"} %>
  </div>
  <div>
    <p><strong>Questions:</strong></p>

    <div id="nested-fields">
      <%= f.simple_fields_for :questions do |question| %>
        <%= render 'question_fields', :f => question %>
      <% end %>

      <div class="links">
        <%= link_to_add_association 'Add Question', f, :questions %>
      </div>
    </div>
  </div>

  <%= f.submit %>
<% end %>

app/views/exams/_question_fields.html.erb
<div class="nested-fields">
  <%= f.label :question_content, "Question" %>
  <%= f.text_area :question_content, :rows => 2, cols: 10 %>
   <%= link_to_remove_association "remove", f %>
  <%= f.simple_fields_for :answers do |answer| %>
    <%= render 'answer_fields', :f => answer %>
  <% end %>
  <p><%= link_to_add_association "Add Answer", f, :answers %></p>
</div>

app/views/exams/_subject.html.erb
<style type="text/css" media="">
.category{
	display:inline-block;
font-weight:300;color:#455358;
font-size:24px;
padding:2px 15px;
background:#efefef;
margin-left:13px;
}
.mastery{
	display:inline-block;
	float:right;
	font-size:24px;
	position:relative;
	right:5px;
	margin-right:8px;
}
</style>
<div>
<div align="center" style="" class="category "><%= params[:category] %></div>
<div class="mastery category"></div>
</div>
<div class="row mybox-container" style="margin-bottom:0 !important;margin:10px;">

	<% counter = 0  %>
	<% accumulator=0  %>
	<% mastery=0  %>
	<% @practises.each do |practise|  %>
<div class="col s12 m3 s3 pad-top">
   <div class="card" style="background-color:white;">
      <div class="card-content">
				<center>
				<h6 class="sub"><%= practise.name  %></h6>
				<div class="practice-info">
					<br />
					<%= link_to 'Practise',practise_path(practise),class:'prac_btn' %>
					<br />
					<br />
					<% RecentScore.where(exam_id: practise.id,user_id: current_user.id).each do |temp_score| %>
						<% accumulator = accumulator+temp_score.temp %>
						<% counter=counter+1  %>
					<% end  %>
					<div style="margin-bottom:6px;" class="test-info">Tests taken:&nbsp;&nbsp;<span><%= Score.where(user_id:current_user.id,exam_id:practise.id).length  %></span></div>
					<div class="progress-info">Score:&nbsp;&nbsp;<span><% if !RecentScore.find_by(:exam_id => practise.id, :user_id => current_user.id).nil? %><%= RecentScore.find_by(:exam_id => practise.id, :user_id => current_user.id).temp %><% else %><%= "N/A" %><% end %></span></div>
				</div>
			</center>
      </div>
   </div>
</div>
<% end  %>

<% if @practises.length != 0  %>
<% number_of_chapters = @practises.length.to_f %>
<% mastery=((accumulator/number_of_chapters)).floor %> 
<% end  %>

<script charset="utf-8">
$(".mastery").html("<span>Mastery&nbsp;</span><%= mastery%>%");
</script>
</div>

<style type="text/css" media="all">
.test-info{
border:1px solid #007aff;
background:#007aff;
padding:4px;
color:white!important;
	border-radius:5px;
}
.progress-info{
	border:1px solid #01579b;
background:white;
padding:4px;
color:black!important;
	border-radius:5px;
}
.test-info span, .progress-info span{

}
.test-info,.progress-info{
color:#444;	
}
.prac_btn{
border:1px solid blue;
padding:8px;
margin-bottom:6px;
	border-radius:5px;
}	
.prac_btn:hover{
	background:blue;
	color:white;
}
.card{
	border-bottom:4px solid red;
}
.sub{
	font-family:hurme_no2-webfont,-apple-system;
	text-transform:uppercase;
	font-size:16px;
}
</style>

app/views/exams/edit.html.erb
m</h1>
<% if @exam.nil? %>
<h1>No exam, here! </h1>
<% else %>
<%= render 'form' %>
<% end %>

app/views/exams/iindex.html.erb
<%# <% if current_user.admin %>
<%#     <% Category.all.each do |category| %>
<%#         <%= link_to category.category, exams_path(category: category.category) %>
<%#     <% end %>
<%# 	<% end %>

</div>
<div>
<style>

		.html{
			font-family:Roboto !important;
		}
    .mdl-button{
        height:30px;
        line-height:29px;
    }
    .listing-exam li{
        background:white;
        padding:7px;
    }
    .listing-exam li:hover{
        background:#fafafa;
    }
    .listing-exam li span{
        float:right;
        font-size:16px;
    }
    .listing-exam span{
        float:right;
    }
    .exam{
        display:inline;
        font-size:26px;
        font-weight:300;
    }
    @media (max-width:600px){
        .exam{
            font-size:24px;
        }
        .fa-arrow-right{
        display:block;
        }
    }
    @media (min-width:601px){
    }
    @media (max-width:450px){
        .exam{
            font-size:18px;
        }
    }
    h1.category{
        text-align:center;  
    }
    @media (max-width:991px){
        h1.category{
        text-align:center;  
        }
    }

</style>
<h1 style="font-weight:200;" class="category"><%= params[:category] %></h1>
    <div class="conetainer-fluid">
        <div class="row">
            <div class="col m12 l8" >
							<% @exams.each do |exam| %>
									<div>	<%= exam.name %></div>
                </div>
							<% end  %>

            </div>
            <div class="col m12 l4" style="">
							   <div class="card" style="background-color:white;">
      <div class="card-content">
				<center>
					<h5>Performance in <%= params[:category] %></h5>
         </center>
				 <br />
				 <center>
					 <h6>COme on this is your performance</h6>
				 </center><br>
      </div>
   </div>


			   <div class="card" style="background-color:white;">
      <div class="card-content">
				<center>
					<h5>Advertisement</h5>
         </center>
				 <br />
				 <center>
					 <h6>This is where paisa comes </h6>
				 </center><br>
      </div>
   </div>



            </div>
        </div>
    </div>

app/views/exams/index.html.erb
<%= render 'welcomes/navbar' %>
<div id="main">
<div class="wrapper">
    <script>
      $(".sidebar-collapse").sideNav();
   </script>
   <div >
      <section id="content" style="padding-top:64px">
         <%= render 'shared/flash' %>
         <style>
            .pad-top i{color:white;font-size: 7em !important;}
         </style>
         <div class="row mybox-container">
<!-- render partial -->
<%= render 'subject'  %>
         </div>
      </section>
   </div>
</div>

app/views/exams/new.html.erb
<h1 class ="createExam">Create new Exam</h1>
<%= render 'form' %>
        
        

app/views/exams/showa.html.erb
<%= @questions.to_json %>